apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- nginx-deployment.yaml
- nginx-svc.yaml
- argocd-notifications-v1.2.1-install.yaml

patchesStrategicMerge:
- argocd-notifications-catalog-v1.2.1-install.yaml


